### ISSUE TITLE
SS 3.1.6 issue Column 'LinkInternal' cannot be null

### ISSUE THREAD

**Issue by nimeso** [webtorque7/link-field#2]
Hey ya! 

I'm trying to upgrade a website using the WTLink field (thanks for all the hard work) 
I'm getting errors :( Happy to pay for your time because this is quite urgent :) cheers heaps!

ERROR [User Error]: Couldn't run query: 
INSERT INTO "ImageContentBox" ("ID", "Caption", "TrackLink", "Track", "AnalyticsCategory", "AnalyticsAction", "AnalyticsLabel", "LinkType", "LinkInternal", "LinkExternal", "LinkEmail", "LinkFile", "LinkTargetBlank", "ImageID") VALUES (26, null, '0', '0', null, null, null, null, null, null, null, null, null, 0) 

Column 'LinkInternal' cannot be null
IN POST /admin/promo-boxes/ContentBox/EditForm/field/ContentBox/item/new/ItemEditForm
Line 598 in D:\wamp\www\hollyford\framework\model\MySQLDatabase.php

Source
======
  589: 	}
  590: 
  591: 	public function databaseError($msg, $errorLevel = E_USER_ERROR) {
  592: 		// try to extract and format query
  593: 		if(preg_match('/Couldn\'t run query: ([^\|]*)\|\s*(.*)/', $msg, $matches)) {
  594: 			$formatter = new SQLFormatter();
  595: 			$msg = "Couldn't run query: \n" . $formatter->formatPlain($matches[1]) . "\n\n" . $matches[2];
  596: 		}
  597: 
* 598: 		user_error($msg, $errorLevel);
  599: 	}
  600: 
  601: 	/**
  602: 	 * Return a boolean type-formatted string
  603: 	 *
  604: 	 * @param array $values Contains a tokenised list of info about this data type

Trace
=====
user_error(Couldn't run query: 
INSERT INTO "ImageContentBox" ("ID", "Caption", "TrackLink", "Track", "AnalyticsCategory", "AnalyticsAction", "AnalyticsLabel", "LinkType", "LinkInternal", "LinkExternal", "LinkEmail", "LinkFile", "LinkTargetBlank", "ImageID") VALUES (26, null, '0', '0', null, null, null, null, null, null, null, null, null, 0) 

Column 'LinkInternal' cannot be null,256)
MySQLDatabase.php:598

MySQLDatabase->databaseError(Couldn't run query: INSERT INTO "ImageContentBox" ("ID", "Caption", "TrackLink", "Track", "AnalyticsCategory", "AnalyticsAction", "AnalyticsLabel", "LinkType", "LinkInternal", "LinkExternal", "LinkEmail", "LinkFile", "LinkTargetBlank", "ImageID") VALUES (26, null, '0', '0', null, null, null, null, null, null, null, null, null, 0) | Column 'LinkInternal' cannot be null,256)
MySQLDatabase.php:150

MySQLDatabase->query(INSERT INTO "ImageContentBox" ("ID", "Caption", "TrackLink", "Track", "AnalyticsCategory", "AnalyticsAction", "AnalyticsLabel", "LinkType", "LinkInternal", "LinkExternal", "LinkEmail", "LinkFile", "LinkTargetBlank", "ImageID") VALUES (26, null, '0', '0', null, null, null, null, null, null, null, null, null, 0))
Database.php:650

SS_Database->manipulate(Array)
DB.php:253

DB::manipulate(Array)
DataObject.php:1269

DataObject->write()
GridFieldDetailForm.php:527

GridFieldDetailForm_ItemRequest->doSave(Array,Form,SS_HTTPRequest)
Form.php:374

Form->httpSubmission(SS_HTTPRequest)
RequestHandler.php:288

RequestHandler->handleAction(SS_HTTPRequest,httpSubmission)
RequestHandler.php:200

RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
RequestHandler.php:222

RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
GridFieldDetailForm.php:102

GridFieldDetailForm->handleItem(GridField,SS_HTTPRequest)
GridField.php:716

GridField->handleRequest(SS_HTTPRequest,DataModel)
RequestHandler.php:222

RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
RequestHandler.php:222

RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
Controller.php:153

Controller->handleRequest(SS_HTTPRequest,DataModel)
LeftAndMain.php:443

LeftAndMain->handleRequest(SS_HTTPRequest,DataModel)
AdminRootController.php:93

AdminRootController->handleRequest(SS_HTTPRequest,DataModel)
Director.php:367

Director::handleRequest(SS_HTTPRequest,Session,DataModel)
Director.php:153

Director::direct(/admin/promo-boxes/ContentBox/EditForm/field/ContentBox/item/new/ItemEditForm,DataModel)
main.php:176

**Comment by webtorque7** [comment]
Module updated for 3.1 support

**Comment by webtorque7** [comment]
Just ran into this issue. Looks like it is an issue in 3.1, the way it handled manipulations changed (for the worse). Looks to have been fixed in 3.2.
